#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  cd "$shome"
  lein figwheel
}

source sub "$BASH_SOURCE" "$@"
